name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        - os: ubuntu-latest
          cache: ~/.cache/deno
        - os: macos-latest
          cache: ~/Library/Caches/deno
        - os: windows-latest
          cache: ~/.deno

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        timeout-minutes: 1
        continue-on-error: true
        uses: actions/cache@v2.1.4
        with:
          path: ${{ matrix.cache }}
          key: deno-${{ runner.os }}-${{ hashFiles('{lib,utils}/{std,x}/**/*.ts') }}
          restore-keys: |
            deno-${{ runner.os }}-${{ hashFiles('{lib,utils}/{std,x}/**/*.ts') }}
            deno-${{ runner.os }}-
            deno-
      - name: Install Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: 1.8.0
      - name: Test
        run: deno test --unstable --allow-all scripts/test.ts
      - name: Prepare for uploading deno cache as artifacts
        env:
          SOURCE: ${{ matrix.cache }}
          TARGET: deno-cache.${{ matrix.os }}.tmp
        run: cp -r "$SOURCE" "$TARGET"
      - name: Upload deno cache as artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          name: deno-cache.${{ matrix.os }}
          path: deno-cache.${{ matrix.os }}.tmp
